### ISSUE TITLE
installation fails on logstash 5.4.0

### ISSUE THREAD

**Issue by pravinpr** [logstash-plugins/logstash-output-jms#6]
I am trying to install this plugin on logstash 5.4.0. I am getting below error:-

> ./bin/logstash-plugin install logstash-output-jms-2.0.4.gem 
Validating logstash-output-jms-2.0.4.gem
Installing logstash-output-jms
Plugin version conflict, aborting
ERROR: Installation Aborted, message: Bundler could not find compatible versions for gem "logstash-core-plugin-api":
  In snapshot (Gemfile.lock):
    logstash-core-plugin-api (= 2.1.12)
  In Gemfile:
    logstash-devutils (>= 0) java depends on
      logstash-core-plugin-api (<= 2.99, >= 2.0) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-output-file (>= 0) java depends on
      logstash-core-plugin-api (< 2.99, >= 2.0.0) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-output-stdout (>= 0) java depends on
      logstash-core-plugin-api (< 2.99, >= 1.60.1) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-filter-dissect (>= 0) java depends on
      logstash-core-plugin-api (<= 2.99, >= 2.1.1) java
    logstash-input-jms (= 3.0.1) java depends on
      logstash-core-plugin-api (<= 2.99, >= 1.60) java
    logstash-output-jms (= 2.0.4) java depends on
      logstash-core-plugin-api (~> 1.0) java
    logstash-core-plugin-api (>= 0) java
Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

**Comment by pravinpr** [comment]
@ph can you please help on this?

**Comment by acchen97** [comment]
@AgentW4C any thoughts on this one?

**Comment by pravinpr** [comment]
Is it because the current build is failing?
I suspect this as the latest input plugin version published in rubygem (https://rubygems.org/gems/logstash-input-jms) is 3.0.1, however, that of output plugin is 2.0.4 (https://rubygems.org/gems/logstash-output-jms).

**Comment by jsvd** [comment]
the tests are incorrect and so are failing, from what I see, the semantic_logger gem which this plugin depends on through the jruby-jms needs to pinned to < 4.0.0 like the input plugin does.

Even after fixing this there are two errors running the spec suite, that can be seen on travis.
I'm definitely up for reviewing a PR that fixes the tests.
